import Head from 'next/head'
import Link from 'next/link'

export default function Home () {
  let data = [
    {
      title: 'iOS Whatsapp',
      link: '/ioswhatsapp'
    },
    {
      title: 'iOS Instagram',
      link: '/ioswhatsapp'
    },
    {
      title: 'iOS Snapchat',
      link: '/ioswhatsapp'
    }
  ]
  return (
    <div>
      <Head>
        <title>Dhimaan</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ul className='flex justify-between flex-col text-xl items-center py-10 space-y-4 text-center mx-10'>
          {data.map((value, index) => (
            <li key={index} className='w-full'>
              <Link href={value.link}>
                <a>
                  <div className='border px-2 py-8 border-black hover:bg-black hover:text-white w-full text-sm md:text-2xl'>
                    {value.title}
                  </div>
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}
